version: '3.8'

services:
  spartial-engineering-frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/programmerdatch/spartial-eng-fe:latest
    ports:
      - "7009:80"
    environment:
      - VITE_API_BASE_URL=https://api.spartial-engineering-group.com/
    restart: unless-stopped
